### ISSUE TITLE
Is there a pure Node.js implementation of ed25519?

### ISSUE THREAD

**Issue by lmatteis** [substack/ed25519-supercop#2]
Is there any particular reason why there isn't a pure implementation of this for node? I'm asking because this is the only native module in my app and packaging my app across platforms is a bit of a pain (having to compile on Windows and Mac computers independently).

**Comment by 1p6** [comment]
Just wrote up [this](https://www.npmjs.com/package/supercop.js) module today. Uses Emscripten to compile the ed25519 implementation that this module uses to pure javascript.

**Comment by substack** [comment]
I added a link to the pure js module to the readme. Great work @1p6!
